name: Docker Mirrors CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * *'

defaults:
  run:
    shell: bash

jobs:
  
  docker-images-mirrors:
    strategy:
      matrix:
        image: [postgis, gdal, qgis, geonetwork, elasticsearch, kibana, redis, logstash, mysql, mongo]
    name: mirror docker image for ${{ matrix.image }}
    env:
      IMAGE_NAME: ${{ matrix.image }}
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Login to dockerhub
      if: ${{  (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request')  }}
      env:
        DOCKERHUB_ALIYUN_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_ALIYUN_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: docker login -u $DOCKERHUB_ALIYUN_USERNAME -p $DOCKERHUB_ALIYUN_PASSWORD registry.cn-hangzhou.aliyuncs.com

    - name: pull and push
      run: |
        make $IMAGE_NAME

